# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    nb_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    nb_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

nb_arm_controller:
  ros__parameters:
    joints:
      - base_bearing
      - shoulder
      - elbow
      - wrist1
      - wrist2
      - wrist3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
nb_gripper_controller:
  ros__parameters:
    joint: gripper_slider1