# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - nb_arm_controller

  nb_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_base1
      - link1.5
      - link2
      - arm_wrist1
      - arm_wrist2
      - arm_wrist3
    action_ns: follow_joint_trajectory
    default: true