# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    nb_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

nb_arm_controller:
  ros__parameters:
    joints:
      - arm_base1
      - link1.5
      - link2
      - arm_wrist1
      - arm_wrist2
      - arm_wrist3
    command_interfaces:
      []
    state_interfaces:
      []