# Default initial positions for nashbot's ros2_control fake system

initial_positions:
  base_bearing: 0.0
  elbow: 0.0
  gripper_slider2: 0.0
  shoulder: 0.0
  wrist1: 0.0
  wrist2: 0.0
  wrist3: 0.0
